language: python
python:
   - "3.6"
jobs:
    include:
      - stage: "Tests"
        name: "Unit and Integration Tests"
        script: python3 -m unittest _test_runner.py
      - script: python3 -m unittest _smoke_test_runner.py
        name: "Smoke Tests"
